FROM ubuntu:22.04
RUN apt update && apt install -y git build-essential cmake python3 python3-pip
RUN git clone https://github.com/ggerganov/llama.cpp.git && cd llama.cpp && make
WORKDIR /llama.cpp
COPY mistral-7b-instruct-v0.1.Q4_K_M.gguf ./models/
ENTRYPOINT ["./main"]